--------------------------------------------------------
--  Arquivo criado - quarta-feira-agosto-20-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento_175\Functions\ACENTO_CORRIGIR.sql
@C:\projetos\jobone\versionamento_175\Functions\ACENTO_RETIRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\BYTES_NOTACAO_RETORNAR.sql
@C:\projetos\jobone\versionamento_175\Functions\CAP_INICIAR.sql
@C:\projetos\jobone\versionamento_175\Functions\CHAR_ESPECIAL_RETIRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\CHARSET_RETORNAR.sql
@C:\projetos\jobone\versionamento_175\Functions\COMPARAR.sql
@C:\projetos\jobone\versionamento_175\Functions\COMPARAR_DATA.sql
@C:\projetos\jobone\versionamento_175\Functions\COORD_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\COORD_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_DIF_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_HORA_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_HORA_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_NASC_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_NASC_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_NASC_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DATA_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DIA_SEMANA_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\DIG_MOD11_RETORNAR.sql
@C:\projetos\jobone\versionamento_175\Functions\EMAIL_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\FLAG_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\FORMATO_RETIRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\HORA_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\HORA_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\IDADE_CALCULAR.sql
@C:\projetos\jobone\versionamento_175\Functions\INTEIRO_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\LEFT_STRING.sql
@C:\projetos\jobone\versionamento_175\Functions\MES_ABREV_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\MES_ANO_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\MES_ANO_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\MES_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\MOEDA_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\MOEDA_EXTENSO_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\MOEDA_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\MOEDA_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\NUMERO_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\NUMERO_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\NUMERO_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\PROX_VALOR_RETORNAR.sql
@C:\projetos\jobone\versionamento_175\Functions\TAXA_CONVERTER.sql
@C:\projetos\jobone\versionamento_175\Functions\TAXA_MOSTRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\TAXA_VALIDAR.sql
@C:\projetos\jobone\versionamento_175\Functions\ULT_VALOR_RETORNAR.sql
@C:\projetos\jobone\versionamento_175\Functions\ZEROS_DIR_RETIRAR.sql
@C:\projetos\jobone\versionamento_175\Functions\ZVL.sql
