--------------------------------------------------------
--  Arquivo criado - quarta-feira-agosto-20-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento_175\Views\V_ALOCACAO_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Views\V_ALOC_USU_CONTRATO_MES.sql
@C:\projetos\jobone\versionamento_175\Views\V_ANALISE_ITENS_ORCAMENTO.sql
@C:\projetos\jobone\versionamento_175\Views\V_APONTAM_ADMIN_PESQ.sql
@C:\projetos\jobone\versionamento_175\Views\V_APONTAM_JOB_PESQ.sql
@C:\projetos\jobone\versionamento_175\Views\V_ATIVIDADES_JOB.sql
@C:\projetos\jobone\versionamento_175\Views\V_AVALIACAO.sql
@C:\projetos\jobone\versionamento_175\Views\V_CLIENTES.sql
@C:\projetos\jobone\versionamento_175\Views\V_CONTRATO_CONSUMO_RESUMO.sql
@C:\projetos\jobone\versionamento_175\Views\V_CONTRATO_ESTIMATIVAS.sql
@C:\projetos\jobone\versionamento_175\Views\V_CONTRATOS.sql
@C:\projetos\jobone\versionamento_175\Views\V_CONTRATO_SERVICOS.sql
@C:\projetos\jobone\versionamento_175\Views\V_CONTRATO_USU_ALOC.sql
@C:\projetos\jobone\versionamento_175\Views\V_CONTRATO_USU_ALOC_DETALHE.sql
@C:\projetos\jobone\versionamento_175\Views\V_CUBO_ITEM_JOB.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_ALOC_DIA.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_ALOC_DIA_USU.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_ALOC_TOTAL.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_ALOC_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_ATRASOS.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_AUSENCIA.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_OVERTIME_DIA.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_OVERTIME_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_OVERTIME_USU_LIVRES.sql
@C:\projetos\jobone\versionamento_175\Views\V_DASH_OPER_TIMESHEET.sql
@C:\projetos\jobone\versionamento_175\Views\V_DOCUMENTO_TASK.sql
@C:\projetos\jobone\versionamento_175\Views\V_ESTADO_CIVIL.sql
@C:\projetos\jobone\versionamento_175\Views\V_EXECUTORES_WORKFLOWS.sql
@C:\projetos\jobone\versionamento_175\Views\V_EXECUTORES_WORKFLOWS_EXEC.sql
@C:\projetos\jobone\versionamento_175\Views\V_FORNECEDORES.sql
@C:\projetos\jobone\versionamento_175\Views\V_HISTORICO.sql
@C:\projetos\jobone\versionamento_175\Views\V_HORAS_ALOC_CTR_X_TIMESHEET.sql
@C:\projetos\jobone\versionamento_175\Views\V_HORAS_VEND_CONTR_UTIL.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOB_CONTATO.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOB_DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOBS.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOBS_ANDAMENTO.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOBS_ANDAMENTO_ALL.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOBS_PREPARACAO.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOBS_PREPARACAO_ALL.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOB_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Views\V_JOB_USUARIO_QTD.sql
@C:\projetos\jobone\versionamento_175\Views\V_MONITORA_DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Views\V_MONITORA_FATURAMENTO_PEND.sql
@C:\projetos\jobone\versionamento_175\Views\V_NEGOCIACAO.sql
@C:\projetos\jobone\versionamento_175\Views\V_NIVEL_IDIOMA.sql
@C:\projetos\jobone\versionamento_175\Views\V_OPORT_GANHAS.sql
@C:\projetos\jobone\versionamento_175\Views\V_OPORTUNIDADES.sql
@C:\projetos\jobone\versionamento_175\Views\V_OS_EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Views\V_PAPEL_PRIV.sql
@C:\projetos\jobone\versionamento_175\Views\V_PAUTA_ATIVIDADES.sql
@C:\projetos\jobone\versionamento_175\Views\V_PAUTA_ATIVIDADES_EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Views\V_PAUTA_ATIVIDADES_EXECUTOR.sql
@C:\projetos\jobone\versionamento_175\Views\V_PAUTA_ATIVIDADES_LISTA.sql
@C:\projetos\jobone\versionamento_175\Views\V_PAUTA_ATIVIDADES_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Views\V_PESSOAS.sql
@C:\projetos\jobone\versionamento_175\Views\V_PESSOA_TIPO.sql
@C:\projetos\jobone\versionamento_175\Views\V_STATUS_JOB.sql
@C:\projetos\jobone\versionamento_175\Views\V_TAREFA_EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Views\V_TIMELINE.sql
@C:\projetos\jobone\versionamento_175\Views\V_TIPO_FLUXO.sql
@C:\projetos\jobone\versionamento_175\Views\V_UNIDADE_FREQ.sql
@C:\projetos\jobone\versionamento_175\Views\V_USU_APONTAM_ATRASADOS.sql
@C:\projetos\jobone\versionamento_175\Views\V_USU_APONTAM_DETALHADO.sql
@C:\projetos\jobone\versionamento_175\Views\V_USUARIOS.sql
@C:\projetos\jobone\versionamento_175\Views\V_USU_PAPEL_ENDER.sql
@C:\projetos\jobone\versionamento_175\Views\V_USU_SEM_APONTAM.sql
@C:\projetos\jobone\versionamento_175\Views\V_WORKFLOW_STATUS.sql
