--------------------------------------------------------
--  DDL for View V_ALOC_USU_CONTRATO_MES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_ALOC_USU_CONTRATO_MES" ("EMPRESA_ID", "CONTRATO_ID", "HORAS_PLANEJ", "HORAS_ALOC", "APELIDO", "ATIVO", "MES", "ANO", "USUARIO_ID", "HORAS_MES", "MES_ABREV_DESC", "EQUIPE_ID", "EQUIPE", "CARGO_ID", "CARGO", "NIVEL", "UNIDADE_NEGOCIO_ID", "UNIDADE_NEGOCIO", "HORAS_ALOCADAS", "HORAS_LIVRES", "PLANEJADO_PERIODO") AS 
  SELECT CO.EMPRESA_ID,
       CO.CONTRATO_ID,
       CH.HORAS_PLANEJ,
       HU.HORAS_ALOC,
       PE.APELIDO,
       PE.FLAG_ATIVO AS ATIVO,
       DA.MES,
       DA.ANO,
       PE.USUARIO_ID,
       (select
NVL(USU.NUM_HORAS_PROD_DIA * 20,NUMERO_CONVERTER(empresa_pkg.parametro_retornar(CO.EMPRESA_ID,'QT_HORAS_MENSAIS')))
from USUARIO USU
WHERE USU.USUARIO_ID = PE.USUARIO_ID) AS HORAS_MES,
       MAX(DECODE(DA.MES,1,'Jan',
                     2,'Fev',
                     3,'Mar',
                     4,'Abr',
                     5,'Mai',
                     6,'Jun',
                     7,'Jul',
                     8,'Ago',
                     9,'Set',
                     10,'Out',
                     11,'Nov',
                        'Dez') || '/' || DA.ANO) AS MES_ABREV_DESC,
       MAX((SELECT DISTINCT LISTAGG(E.EQUIPE_ID,', ') WITHIN GROUP (ORDER BY E.EQUIPE_ID)
          FROM EQUIPE E,
               EQUIPE_USUARIO EU
         WHERE E.EQUIPE_ID   = EU.EQUIPE_ID
           AND EU.USUARIO_ID = HU.USUARIO_ID)) AS EQUIPE_ID,
       MAX((SELECT DISTINCT LISTAGG(E.NOME,', ') WITHIN GROUP (ORDER BY E.NOME)
          FROM EQUIPE E,
               EQUIPE_USUARIO EU
         WHERE E.EQUIPE_ID   = EU.EQUIPE_ID
           AND EU.USUARIO_ID = HU.USUARIO_ID)) AS EQUIPE,
       MAX((SELECT C.CARGO_ID
          FROM CARGO C,
               USUARIO_CARGO UC
        WHERE C.CARGO_ID     = UC.CARGO_ID
          AND UC.USUARIO_ID  = HU.USUARIO_ID
          AND UC.DATA_FIM    IS NULL)) AS CARGO_ID,
       MAX((SELECT C.NOME
          FROM CARGO C,
               USUARIO_CARGO UC
        WHERE C.CARGO_ID     = UC.CARGO_ID
          AND UC.USUARIO_ID  = HU.USUARIO_ID
          AND UC.DATA_FIM    IS NULL)) AS CARGO,
       MAX(CH.NIVEL) AS NIVEL,
       MAX((SELECT DISTINCT LISTAGG(UN.UNIDADE_NEGOCIO_ID,', ') WITHIN GROUP (ORDER BY UN.UNIDADE_NEGOCIO_ID)
          FROM UNIDADE_NEGOCIO     UN,
               UNIDADE_NEGOCIO_USU UE
         WHERE UN.UNIDADE_NEGOCIO_ID = UE.UNIDADE_NEGOCIO_ID
           AND UE.USUARIO_ID         = HU.USUARIO_ID
           AND UN.EMPRESA_ID         = CO.EMPRESA_ID)) AS UNIDADE_NEGOCIO_ID,
       MAX((SELECT DISTINCT LISTAGG(UN.NOME,', ') WITHIN GROUP (ORDER BY UN.NOME)
          FROM UNIDADE_NEGOCIO     UN,
               UNIDADE_NEGOCIO_USU UE
         WHERE UN.UNIDADE_NEGOCIO_ID = UE.UNIDADE_NEGOCIO_ID
           AND UE.USUARIO_ID         = HU.USUARIO_ID
           AND UN.EMPRESA_ID         = CO.EMPRESA_ID)) AS UNIDADE_NEGOCIO,
       MAX((SELECT SUM(CH2.HORAS_PLANEJ)
      FROM DIA_ALOCACAO DA2,
           CONTRATO_HORAS_USU CHU2,
           CONTRATO_HORAS CH2
      WHERE DA2.USUARIO_ID = CHU2.USUARIO_ID
      AND CHU2.CONTRATO_HORAS_ID = CH2.CONTRATO_HORAS_ID
      AND TO_CHAR(DA2.DATA,'MM/YY') = TO_CHAR(DA.DATA,'MM/YY')
      AND CHU2.USUARIO_ID = HU.USUARIO_ID)) AS HORAS_ALOCADAS,
      MAX((SELECT(
(select
NVL(NUMERO_CONVERTER(empresa_pkg.parametro_retornar(CO.EMPRESA_ID,'NUM_HORAS_PRODUTIVAS')) * 20,NUMERO_CONVERTER(empresa_pkg.parametro_retornar(CO.EMPRESA_ID,'QT_HORAS_MENSAIS')))
from dual)
-
(SELECT
    SUM(CH2.HORAS_PLANEJ)
FROM DIA_ALOCACAO DA2,
     CONTRATO_HORAS_USU CHU2,
     CONTRATO_HORAS CH2
WHERE DA2.USUARIO_ID = CHU2.USUARIO_ID
AND CHU2.CONTRATO_HORAS_ID = CH2.CONTRATO_HORAS_ID
AND TO_CHAR(DA2.DATA,'MM/YY') = TO_CHAR(DA.DATA,'MM/YY')
AND CHU2.USUARIO_ID = HU.USUARIO_ID))
FROM DUAL))  AS HORAS_LIVRES,
       NULL AS PLANEJADO_PERIODO
  FROM CONTRATO CO,
       CONTRATO_HORAS CH,
       CONTRATO_HORAS_USU HU,
       PESSOA             PE,
       DIA_ALOCACAO       DA
 WHERE CO.CONTRATO_ID       = CH.CONTRATO_ID
   AND CH.CONTRATO_HORAS_ID = HU.CONTRATO_HORAS_ID
   AND HU.USUARIO_ID        = PE.USUARIO_ID
   AND HU.USUARIO_ID        = DA.USUARIO_ID
 GROUP
    BY CO.EMPRESA_ID,
       CO.CONTRATO_ID,
       CH.HORAS_PLANEJ,
       HU.HORAS_ALOC,
       PE.APELIDO,
       PE.FLAG_ATIVO,
       DA.MES,
       DA.ANO,
       PE.USUARIO_ID

;
