--------------------------------------------------------
--  DDL for View V_CONTRATO_USU_ALOC
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_CONTRATO_USU_ALOC" ("USUARIO_ID", "NOME", "ATIVO", "CONTRATO_ID", "EMPRESA_ID", "NIVEL", "MES", "ANO", "MES_ANO", "EQUIPE_ID", "EQUIPE", "CARGO_ID", "CARGO", "UNIDADE_NEGOCIO_ID", "UNIDADE_NEGOCIO", "HORAS_MES", "HORAS_ALOC_PLANEJADA_MES", "HORAS_LIVRES") AS 
  SELECT PE.USUARIO_ID,
       PE.APELIDO AS NOME,
       USU.FLAG_ATIVO AS ATIVO,
       CO.CONTRATO_ID,
       CO.EMPRESA_ID,
       CH.NIVEL AS NIVEL,
       TO_CHAR(CH.DATA, 'MM') AS MES,
       TO_CHAR(CH.DATA, 'YYYY') AS ANO,
       TO_CHAR(CH.DATA, 'MON/YYYY', 'nls_language ="BRAZILIAN PORTUGUESE"')AS MES_ANO,
       (SELECT DISTINCT LISTAGG(E.EQUIPE_ID,', ') WITHIN GROUP (ORDER BY E.EQUIPE_ID)
          FROM EQUIPE E,
               EQUIPE_USUARIO EU
         WHERE E.EQUIPE_ID   = EU.EQUIPE_ID
           AND EU.USUARIO_ID = PE.USUARIO_ID) AS EQUIPE_ID,
       (SELECT DISTINCT LISTAGG(E.NOME,', ') WITHIN GROUP (ORDER BY E.NOME)
          FROM EQUIPE E,
               EQUIPE_USUARIO EU
         WHERE E.EQUIPE_ID   = EU.EQUIPE_ID
           AND EU.USUARIO_ID = PE.USUARIO_ID) AS EQUIPE,
       (SELECT C.CARGO_ID
          FROM CARGO C,
               USUARIO_CARGO UC
        WHERE C.CARGO_ID     = UC.CARGO_ID
          AND UC.USUARIO_ID  = PE.USUARIO_ID
          AND UC.DATA_FIM    IS NULL) AS CARGO_ID,
       (SELECT C.NOME
          FROM CARGO C,
               USUARIO_CARGO UC
        WHERE C.CARGO_ID     = UC.CARGO_ID
          AND UC.USUARIO_ID  = PE.USUARIO_ID
          AND UC.DATA_FIM    IS NULL) AS CARGO,
          (SELECT DISTINCT LISTAGG(UN.UNIDADE_NEGOCIO_ID,', ') WITHIN GROUP (ORDER BY UN.UNIDADE_NEGOCIO_ID)
          FROM UNIDADE_NEGOCIO     UN,
               UNIDADE_NEGOCIO_USU UE
         WHERE UN.UNIDADE_NEGOCIO_ID = UE.UNIDADE_NEGOCIO_ID
           AND UE.USUARIO_ID         = PE.USUARIO_ID
           AND UN.EMPRESA_ID         = CO.EMPRESA_ID) AS UNIDADE_NEGOCIO_ID,
       (SELECT DISTINCT LISTAGG(UN.NOME,', ') WITHIN GROUP (ORDER BY UN.NOME)
          FROM UNIDADE_NEGOCIO     UN,
               UNIDADE_NEGOCIO_USU UE
         WHERE UN.UNIDADE_NEGOCIO_ID = UE.UNIDADE_NEGOCIO_ID
           AND UE.USUARIO_ID         = PE.USUARIO_ID
           AND UN.EMPRESA_ID         = CO.EMPRESA_ID) AS UNIDADE_NEGOCIO,
         (SELECT NVL(USU.NUM_HORAS_PROD_DIA * 20,NUMERO_CONVERTER(empresa_pkg.parametro_retornar(CO.EMPRESA_ID,'QT_HORAS_MENSAIS')))
         FROM USUARIO USU
         WHERE USU.USUARIO_ID = PE.USUARIO_ID) AS HORAS_MES,
         /*
          NULL AS HORAS_PLANEJADAS_PERIODO,
          NULL AS HORAS_LIVRES_PERIODO,
          NULL AS PORC_PLANEJADAS_PERIODO,*/
      (SELECT SUM(CHU2.HORAS_ALOC)
      FROM CONTRATO CON,
           CONTRATO_HORAS_USU CHU2,
           CONTRATO_HORAS CH2
      WHERE CON.CONTRATO_ID = CH2.CONTRATO_ID
      AND CH2.CONTRATO_HORAS_ID = CHU2.CONTRATO_HORAS_ID
      AND TO_CHAR(CH2.DATA,'MM/YY') = TO_CHAR(CH.DATA,'MM/YY')
      AND CHU2.USUARIO_ID = PE.USUARIO_ID
      AND CON.CONTRATO_ID = CO.CONTRATO_ID
      AND CON.EMPRESA_ID = CO.EMPRESA_ID) AS HORAS_ALOC_PLANEJADA_MES,
      (SELECT(
      (SELECT NVL(USU.NUM_HORAS_PROD_DIA * 20,NUMERO_CONVERTER(empresa_pkg.parametro_retornar(CO.EMPRESA_ID,'QT_HORAS_MENSAIS')))
         FROM USUARIO USU
         WHERE USU.USUARIO_ID = PE.USUARIO_ID)
      -
      (SELECT
          SUM(CHU2.HORAS_ALOC)
      FROM CONTRATO CON,
           CONTRATO_HORAS_USU CHU2,
           CONTRATO_HORAS CH2
      WHERE CON.CONTRATO_ID = CH2.CONTRATO_ID
      AND CH2.CONTRATO_HORAS_ID = CHU2.CONTRATO_HORAS_ID
      AND TO_CHAR(CH2.DATA,'MM/YY') = TO_CHAR(CH.DATA,'MM/YY')
      AND CHU2.USUARIO_ID = PE.USUARIO_ID
      AND CON.CONTRATO_ID = CO.CONTRATO_ID))
      FROM DUAL)  AS HORAS_LIVRES
      --NULL AS PLANEJADO_PERIODO
  FROM CONTRATO           CO,
       CONTRATO_HORAS     CH,
       CONTRATO_HORAS_USU HU,
       USUARIO            USU,
       PESSOA             PE
 WHERE CO.CONTRATO_ID       = CH.CONTRATO_ID
   AND CH.CONTRATO_HORAS_ID = HU.CONTRATO_HORAS_ID
   AND HU.USUARIO_ID        = PE.USUARIO_ID
   AND PE.USUARIO_ID        = USU.USUARIO_ID
   GROUP BY
       PE.USUARIO_ID,
       PE.APELIDO,
       USU.FLAG_ATIVO,
       CO.CONTRATO_ID,
       CO.EMPRESA_ID,
       CH.NIVEL,
       CH.DATA

;
