--------------------------------------------------------
--  DDL for View V_PAUTA_ATIVIDADES_EXECUTOR
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_PAUTA_ATIVIDADES_EXECUTOR" ("EMPRESA_ID", "COD_OBJETO", "OBJETO_ID", "ITEM_CRONO_ID", "CLIENTE_ESPECIFICO", "CLIENTE", "JOB_ID", "ATIVIDADE_TIPO", "ATIVIDADE_COR_NO_QUADRO", "ATIVIDADE_NUMERO", "ATIVIDADE_DESCRICAO", "ATIVIDADE_DESCRICAO_SEM_NUMERO", "ATIVIDADE_METADADOS", "STATUS", "STATUS_CODIGO", "PRAZO", "PRAZO_FMT", "PRAZO_COR", "PRAZO_INTERNO", "PRAZO_INTERNO_FMT", "PRAZO_INTERNO_COR", "EQUIPE", "EQUIPE_ID", "EXECUTOR_ID", "EXECUTOR_COR", "COMENT_STATUS", "COMENT_STATUS_AUTOR", "COMENT_STATUS_DATA", "COMENT_STATUS_DATA_FMT", "DATA_CONCLUSAO", "DATA_ALOC_USUARIO", "INICIAR_SOMENTE_EM", "DATA_INICIO_ND", "REFACAO") AS 
  SELECT MOS.EMPRESA_ID,
       MOS.COD_OBJETO,
       MOS.OBJETO_ID,
       MOS.ITEM_CRONO_ID,
       MOS.CLIENTE_ESPECIFICO AS CLIENTE_ESPECIFICO,
       NVL((SELECT LISTAGG(GR.NOME,', ') WITHIN GROUP (ORDER BY GR.NOME)
              FROM GRUPO GR
             INNER
              JOIN GRUPO_PESSOA GP ON GR.GRUPO_ID = GP.GRUPO_ID
             WHERE GP.PESSOA_ID = MOS.CLIENTE
               AND GR.FLAG_AGRUPA_CNPJ = 'S'), MOS.CLIENTE_ESPECIFICO) AS CLIENTE,
       MOS.JOB_ID,
       MOS.ATIVIDADE_TIPO,
       MOS.ATIVIDADE_COR_NO_QUADRO,
       ORDEM_SERVICO_PKG.NUMERO_FORMATAR(MOS.OBJETO_ID) AS ATIVIDADE_NUMERO,
       ORDEM_SERVICO_PKG.NUMERO_FORMATAR(MOS.OBJETO_ID) || ' ' || MOS.ATIVIDADE_DESCRICAO_SEM_NUMERO AS ATIVIDADE_DESCRICAO,
       MOS.ATIVIDADE_DESCRICAO_SEM_NUMERO,
       (SELECT LISTAGG(V.VALOR_ATRIBUTO,', ') WITHIN GROUP (ORDER BY M.ORDEM)
          FROM OS_ATRIBUTO_VALOR V
         INNER
          JOIN METADADO M ON M.METADADO_ID = V.METADADO_ID
         WHERE M.FLAG_NA_LISTA = 'S'
           AND V.ORDEM_SERVICO_ID = MOS.OBJETO_ID) AS ATIVIDADE_METADADOS,
       DECODE(MOS.STATUS,'CONC',UTIL_PKG.DESC_RETORNAR('status_os',MOS.STATUS),
                                UTIL_PKG.DESC_RETORNAR('status_os',MOS.STATUS) ||
                                DECODE(MOS.FLAG_RECUSADA, 'S',' (Recusado)','')) AS STATUS,
       MOS.STATUS_CODIGO,
       MOS.PRAZO,
       DATA_MOSTRAR(MOS.PRAZO) AS PRAZO_FMT,
       CASE
          WHEN MOS.STATUS_CODIGO IN ('PREP','DIST','ACEI','EMEX','AVAL','EXEC','EMAP','STAN') THEN
             CASE
                WHEN MOS.PRAZO <= SYSDATE THEN 'vermelho'
                WHEN MOS.PRAZO > SYSDATE AND MOS.PRAZO < TRUNC(SYSDATE+1) THEN 'amarelo'
             ELSE 'branco'
             END
          ELSE 'branco'
       END AS PRAZO_COR,
       MOS.PRAZO_INTERNO,
       DATA_MOSTRAR(MOS.PRAZO_INTERNO) AS PRAZO_INTERNO_FMT,
       CASE
          WHEN MOS.STATUS IN ('DIST','ACEI','EMEX','AVAL') THEN
             CASE
                WHEN MOS.PRAZO_INTERNO <= SYSDATE THEN 'vermelho'
                WHEN MOS.PRAZO_INTERNO > SYSDATE AND MOS.PRAZO_INTERNO < TRUNC(SYSDATE+1) THEN 'amarelo'
             ELSE 'branco'
             END
           ELSE 'branco'
       END AS PRAZO_INTERNO_COR,
       NVL((SELECT DISTINCT LISTAGG(NOME,', ') WITHIN GROUP (ORDER BY NOME)
              FROM (SELECT DISTINCT E.NOME
                      FROM EQUIPE E
                     INNER
                      JOIN EQUIPE_USUARIO X ON X.EQUIPE_ID = E.EQUIPE_ID
                     INNER
                      JOIN OS_USUARIO O ON O.USUARIO_ID = X.USUARIO_ID
                     WHERE O.ORDEM_SERVICO_ID = MOS.OBJETO_ID
                       AND E.EMPRESA_ID = MOS.EMPRESA_ID
                       AND O.USUARIO_ID = EX.USUARIO_ID
                       AND X.FLAG_MEMBRO = 'S')),'-') AS EQUIPE,
       NVL((SELECT DISTINCT LISTAGG(EQUIPE_ID,', ') WITHIN GROUP (ORDER BY NOME)
              FROM (SELECT DISTINCT E.EQUIPE_ID, E.NOME
                      FROM EQUIPE E
                     INNER
                      JOIN EQUIPE_USUARIO X ON X.EQUIPE_ID = E.EQUIPE_ID
                     INNER
                      JOIN OS_USUARIO O ON O.USUARIO_ID = X.USUARIO_ID
                     WHERE O.ORDEM_SERVICO_ID = MOS.OBJETO_ID
                       AND E.EMPRESA_ID = MOS.EMPRESA_ID
                       AND O.USUARIO_ID = EX.USUARIO_ID
                       AND X.FLAG_MEMBRO = 'S')),'-') AS EQUIPE_ID,
       EX.USUARIO_ID AS EXECUTOR_ID,
       EX.EXECUTOR_COR,
       NVL(MOS.COMENT_STATUS,'-') AS COMENT_STATUS,
       NVL((SELECT P.APELIDO
              FROM PESSOA P
             WHERE P.USUARIO_ID = MOS.USUARIO_SITUACAO_ID),'-') AS COMENT_STATUS_AUTOR,
       MOS.COMENT_STATUS_DATA AS COMENT_STATUS_DATA,
       DATA_MOSTRAR(MOS.COMENT_STATUS_DATA_FMT) AS COMENT_STATUS_DATA_FMT,
       MOS.DATA_CONCLUSAO AS DATA_CONCLUSAO,
       (SELECT MIN(OU.DATA)
         FROM OS_USUARIO_DATA OU
        WHERE OU.ORDEM_SERVICO_ID = MOS.OBJETO_ID) AS DATA_ALOC_USUARIO,
       MOS.DATA_DEMANDA AS INICIAR_SOMENTE_EM,
       CASE
         WHEN MOS.DATA_DEMANDA IS NULL THEN
           'DATA INICIO NAO DEFINIDA'
       END AS DATA_INICIO_ND,
         CASE
            WHEN MOS.QTD_REFACAO = 0 OR MOS.QTD_REFACAO IS NULL THEN
               '-'
            ELSE
               TO_CHAR(MOS.QTD_REFACAO)
          END AS REFACAO
  FROM MV_ORDEM_SERVICO MOS,
      (SELECT DISTINCT
              MU.USUARIO_ID,
              OS.ORDEM_SERVICO_ID,
              DECODE(OU.STATUS, 'EXEC', 'cinza', 'branco') AS EXECUTOR_COR
         FROM MV_USUARIO     MU,
              OS_USUARIO     OU,
              ORDEM_SERVICO  OS,
              JOB            JO
        WHERE (MU.USUARIO_ID       = OU.USUARIO_ID AND OU.TIPO_ENDER = 'EXE')
          AND OU.ORDEM_SERVICO_ID = OS.ORDEM_SERVICO_ID
          AND OS.JOB_ID           = JO.JOB_ID) EX
 WHERE MOS.OBJETO_ID = EX.ORDEM_SERVICO_ID
UNION ALL
SELECT MTA.EMPRESA_ID,
       MTA.COD_OBJETO,
       MTA.OBJETO_ID,
       MTA.ITEM_CRONO_ID,
       MTA.CLIENTE_ESPECIFICO  AS CLIENTE_ESPECIFICO,
       NVL((SELECT LISTAGG(GR.NOME,', ') WITHIN GROUP (ORDER BY GR.NOME)
              FROM GRUPO GR
             INNER
              JOIN GRUPO_PESSOA GP ON GR.GRUPO_ID = GP.GRUPO_ID
             WHERE GP.PESSOA_ID = MTA.CLIENTE
               AND GR.FLAG_AGRUPA_CNPJ = 'S'), MTA.CLIENTE_ESPECIFICO) AS CLIENTE,
       MTA.JOB_ID,
       MTA.ATIVIDADE_TIPO,
       MTA.ATIVIDADE_COR_NO_QUADRO,
       TAREFA_PKG.NUMERO_FORMATAR(MTA.OBJETO_ID) AS ATIVIDADE_NUMERO,
       TAREFA_PKG.NUMERO_FORMATAR(MTA.OBJETO_ID) || ' ' || MTA.ATIVIDADE_DESCRICAO_SEM_NUMERO AS ATIVIDADE_DESCRICAO,
       MTA.ATIVIDADE_DESCRICAO_SEM_NUMERO,
       (SELECT LISTAGG(V.VALOR_ATRIBUTO,', ') WITHIN GROUP (ORDER BY M.ORDEM)
          FROM TAREFA_TP_ATRIB_VALOR V
         INNER
          JOIN TAREFA_TIPO_PRODUTO T ON T.TAREFA_TIPO_PRODUTO_ID = V.TAREFA_TIPO_PRODUTO_ID
         INNER
          JOIN METADADO M ON M.METADADO_ID = V.METADADO_ID
         WHERE M.FLAG_NA_LISTA = 'S'
           AND T.TAREFA_ID = MTA.OBJETO_ID) AS ATIVIDADE_METADADOS,
       util_pkg.desc_retornar('status_tarefa',MTA.status) AS STATUS,
       MTA.STATUS_CODIGO,
       MTA.PRAZO,
       DATA_MOSTRAR(MTA.PRAZO) AS PRAZO_FMT,
       CASE
          WHEN MTA.PRAZO <= SYSDATE THEN 'vermelho'
          WHEN MTA.PRAZO > SYSDATE AND MTA.PRAZO < TRUNC(SYSDATE+1) THEN 'amarelo'
          ELSE 'branco'
       END AS PRAZO_COR,
       NULL AS PRAZO_INTERNO,
       NULL AS PRAZO_INTERNO_FMT,
       'branco' AS PRAZO_INTERNO_COR,
       NVL((SELECT LISTAGG(NOME,', ') WITHIN GROUP (ORDER BY NOME)
              FROM (SELECT DISTINCT E.NOME
                      FROM EQUIPE E
                     INNER
                      JOIN EQUIPE_USUARIO X ON X.EQUIPE_ID = E.EQUIPE_ID
                     INNER
                      JOIN TAREFA_USUARIO I ON (X.USUARIO_ID = I.USUARIO_PARA_ID OR X.USUARIO_ID = MTA.SOLICITANTE_ID)
                     WHERE I.TAREFA_ID = MTA.OBJETO_ID
                       AND E.EMPRESA_ID = MTA.EMPRESA_ID
                       AND X.USUARIO_ID = ET.USUARIO_ID
                       AND X.FLAG_MEMBRO = 'S')),'-') AS EQUIPE,
       NVL((SELECT LISTAGG(EQUIPE_ID,', ') WITHIN GROUP (ORDER BY NOME)
              FROM (SELECT DISTINCT E.EQUIPE_ID, E.NOME
                      FROM EQUIPE E
                     INNER
                      JOIN EQUIPE_USUARIO X ON X.EQUIPE_ID = E.EQUIPE_ID
                     INNER
                      JOIN TAREFA_USUARIO I ON (X.USUARIO_ID = I.USUARIO_PARA_ID OR X.USUARIO_ID = MTA.SOLICITANTE_ID)
                     WHERE I.TAREFA_ID  = MTA.OBJETO_ID
                       AND E.EMPRESA_ID = MTA.EMPRESA_ID
                       AND X.USUARIO_ID = ET.USUARIO_ID
                       AND X.FLAG_MEMBRO = 'S')),'-') AS EQUIPE_ID,
       ET.USUARIO_ID AS EXECUTOR_ID,
       ET.EXECUTOR_COR,
       NVL(MTA.COMENT_STATUS,'-') AS COMENT_STATUS,
       NVL((SELECT P.APELIDO
              FROM PESSOA P
             WHERE P.USUARIO_ID = MTA.USUARIO_SITUACAO_ID),'-') AS COMENT_STATUS_AUTOR,
       MTA.COMENT_STATUS_DATA AS COMENT_STATUS_DATA,
       DATA_MOSTRAR(MTA.COMENT_STATUS_DATA_FMT) AS COMENT_STATUS_DATA_FMT,
       MTA.DATA_CONCLUSAO AS DATA_CONCLUSAO,
       NULL AS DATA_ALOC_USUARIO,
       NULL AS ASINICIAR_SOMENTE_EM,
       NULL AS DATA_INICIO_ND,
       '-' AS REFACAO
  FROM MV_TAREFA MTA,
       (SELECT DISTINCT
               MU.USUARIO_ID,
               TA.TAREFA_ID,
               DECODE(TU.STATUS, 'EXEC', 'cinza', 'branco') AS EXECUTOR_COR
          FROM MV_USUARIO     MU,
               TAREFA_USUARIO TU,
               TAREFA         TA
        WHERE (MU.USUARIO_ID  = TU.USUARIO_PARA_ID OR (MU.USUARIO_ID = TA.USUARIO_DE_ID AND TA.STATUS = 'EXEC'))
          AND TU.TAREFA_ID    = TA.TAREFA_ID) ET
 WHERE MTA.OBJETO_ID = ET.TAREFA_ID

;
