--------------------------------------------------------
--  Arquivo criado - quarta-feira-agosto-20-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento_175\Packages\Spec\ABATIMENTO_CTR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ABATIMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ADIANT_DESP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\APONTAM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\APONTAM_PROGR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\AREA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ARQUIVO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\BRIEFING_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CAMPANHA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CARGA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CARGO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CARTA_ACORDO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CENARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CEP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CNPJ_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\COMENTARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\COMUNICADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CONDICAO_PAGTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CONTRATO_ELAB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CONTRATO_FISICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CONTRATO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\COTACAO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CPF_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\CRONOGRAMA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\DEPARTAMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\DICIONARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\DICION_EMP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\DOCUMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\EMPRESA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\EQUIPE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\EVENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\FAIXA_APROV_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\FATURAMENTO_CTR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\FATURAMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\FERIADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\FI_BANCO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\FLEX_PAPER_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\GRUPO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\HISTORICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IMPOSTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_ADNNET_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_APOLO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_CIGAM_ANT_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_CIGAM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_CONTROLE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ITEM_DECUP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ITEM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_JOBONE_SELF_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_PORTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_PROTHEUS_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\IT_SAP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\JOB_HORAS_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\JOB_PECA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\LIMPEZA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\LINK_DIRETO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\METADADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\MI_CARGA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\MILESTONE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\MOD_CRONO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\NATUREZA_ITEM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\NATUREZA_OPER_FATUR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\NOTA_FISCAL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\OPORTUNIDADE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ORCAMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\ORDEM_SERVICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PAINEL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PAPEL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PARCELA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PESQUISA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PESSOA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PRECO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PRODUTO_CLIENTE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\PRODUTO_FISCAL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\QUADRO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\RAFAEL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\REGRA_COENDER_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\RELATORIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\RESULT_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SALARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SERVICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SETOR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SISTEMA_EXTERNO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SISTEMA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SOAP_API_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\SOBRA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\STATUS_AUX_JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\STATUS_AUX_OPORT_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TAREFA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TASK_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_APONTAM_JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_APONTAM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_ARQUIVO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_CONTRATO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_DADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_DOCUMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_FINANCEIRO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_OS_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_PRODUTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\TIPO_TAREFA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\UNIDADE_NEGOCIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\USUARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\UTIL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\VOLUME_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\WEBSERVICE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Spec\WEBSERVICEUTILS_PKG.sql
