--------------------------------------------------------
--  Arquivo criado - quarta-feira-agosto-20-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento_175\Packages\Body\ABATIMENTO_CTR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ABATIMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ADIANT_DESP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\APONTAM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\APONTAM_PROGR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\AREA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ARQUIVO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\BRIEFING_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CAMPANHA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CARGA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CARGO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CARTA_ACORDO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CENARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CEP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CNPJ_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\COMENTARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\COMUNICADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CONDICAO_PAGTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CONTRATO_ELAB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CONTRATO_FISICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CONTRATO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\COTACAO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CPF_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\CRONOGRAMA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\DEPARTAMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\DICIONARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\DICION_EMP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\DOCUMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\EMPRESA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\EQUIPE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\EVENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\FAIXA_APROV_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\FATURAMENTO_CTR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\FATURAMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\FERIADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\FI_BANCO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\FLEX_PAPER_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\GRUPO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\HISTORICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IMPOSTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_ADNNET_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_APOLO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_CIGAM_ANT_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_CIGAM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_CONTROLE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ITEM_DECUP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ITEM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_JOBONE_SELF_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_PORTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_PROTHEUS_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\IT_SAP_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\JOB_HORAS_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\JOB_PECA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\LIMPEZA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\LINK_DIRETO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\METADADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\MI_CARGA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\MILESTONE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\MOD_CRONO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\NATUREZA_ITEM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\NATUREZA_OPER_FATUR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\NOTA_FISCAL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\OPORTUNIDADE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ORCAMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\ORDEM_SERVICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PAINEL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PAPEL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PARCELA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PESQUISA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PESSOA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PRECO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PRODUTO_CLIENTE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\PRODUTO_FISCAL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\QUADRO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\RAFAEL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\REGRA_COENDER_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\RELATORIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SALARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SERVICO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SETOR_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SISTEMA_EXTERNO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SISTEMA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SOAP_API_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\SOBRA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\STATUS_AUX_JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\STATUS_AUX_OPORT_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TAREFA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TASK_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_APONTAM_JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_APONTAM_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_ARQUIVO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_CONTRATO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_DADO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_DOCUMENTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_FINANCEIRO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_JOB_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_OS_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_PRODUTO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\TIPO_TAREFA_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\UNIDADE_NEGOCIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\USUARIO_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\UTIL_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\VOLUME_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\WEBSERVICE_PKG.sql
@C:\projetos\jobone\versionamento_175\Packages\Body\WEBSERVICEUTILS_PKG.sql
