--------------------------------------------------------
--  Arquivo criado - quarta-feira-agosto-20-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento_175\Sequences\NOTA_FISCAL_PAGTO_SEQ.sql
@C:\projetos\jobone\versionamento_175\Sequences\PLSQL_PROFILER_RUNNUMBER.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ABATIMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ACAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ADIANT_DESP.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ADIANT_REALIZ.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_AGENCIA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_AJUSTE_JOB.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_APONTAM_DATA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_APONTAM_DATA_EV.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_APONTAM_ENCE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_APONTAM_HORA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_APONTAM_PROGR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_AREA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_AVAL_FORNEC.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_BRIEF_HIST.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_BRIEFING.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CAMPANHA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CARGO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CARTA_ACORDO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CATEGORIA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO_EMPRESA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO_MOD_CONTR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO_SERVICO_HORAS.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO_SERVICO_ITEM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CENARIO_SERVICO_USU.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CLASSE_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COMENTARIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COMUNICADO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONDICAO_PAGTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTEXTO_CRONO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_ELAB.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_FIS_HIST.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_FISICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_HORAS.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_HORAS_USU.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_ITEM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CONTRATO_SERV_VALOR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO_ITEM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO_PESSOA_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO_PESSOA_ITEM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO_PESSOA_LINK.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_COTACAO_PESSOA_VERSAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CRONOGRAMA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_CT_TRANSICAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DEPARTAMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DESP_REALIZ.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DEVOL_REALIZ.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DIA_ALOCACAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DIA_SEMANA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DICION_EMP.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DICION_EMP_VAL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_DUPLICATA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EMAIL_CARTA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EMAIL_HIST.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EMPRESA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ERRO_LOG.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EVENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EVENTO_CONFIG.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_EVENTO_MOTIVO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FAIXA_APROV.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FATURAMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FERIADO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FI_BANCO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FI_TIPO_IMPOSTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FI_TIPO_IMPOSTO_FAIXA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FI_TIPO_IMPOSTO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_FREQUENCIA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_GRUPO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_GRUPO_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_HIST_ENDER.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_HISTORICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_HIST_SENHA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_IMPOSTO_NOTA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_INBOX.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_INTERACAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_ABAT.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_ADIANT.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_CARTA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_CRONO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_DECUP.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_FATUR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_HIST.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_NOTA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ITEM_SOBRA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_JOB.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_JOB_HORAS.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_JOB_PECA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_JOB_RECEITA_CTR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_JOB_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_LANCAMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_LINK_DIRETO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_METADADO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_CARGA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_CARGA_DESCARTE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_CRIT_SEC.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_DAYPART.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MILESTONE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_METAS_DIGITAL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_METAS_OOH.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_METAS_PRINT.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_METAS_RADIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_METAS_TV.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_PI.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MI_VERSAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MOD_CRONO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_MOD_ITEM_CRONO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NATUREZA_ITEM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NATUREZA_OPER_FATUR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTA_FISCAL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICACAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICA_CONFIG.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICA_DESLIGA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICA_FILA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICA_FILA_EMAIL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICA_FILA_USU.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NOTIFICA_HIST.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_NUM_DOC.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OPORT_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OPORTUNIDADE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ORCAMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_ORDEM_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OS_AFAZER.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OS_ESTIM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OS_EVENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OS_HORAS.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OS_LINK.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_OS_NEGOCIACAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PADRAO_PLANILHA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PAINEL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PAPEL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PARAMETRO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PARCELA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PARCELA_CARTA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PARCELA_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PARCELA_FATUR_CTR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PARCELA_NF.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PESQUISA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PESSOA_HOMOLOG.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PESSOA_LINK.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PREFERENCIA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PRIVILEGIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PRODUTO_CLIENTE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_PRODUTO_FISCAL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_QUADRO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_QUADRO_COLUNA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_REGRA_COENDER.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_REL_APON_MENS.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_REL_FLUXO_CHECKIN.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_REPET_GRUPO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SALARIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SALARIO_CARGO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SETOR.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SISTEMA_EXTERNO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SIST_EXT_PARAMETRO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SOBRA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_SOLICIT_CASTING.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_STATUS_AUX_JOB.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_STATUS_AUX_OPORT.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAB_FERIADO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAB_PRECO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAREFA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAREFA_AFAZER.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAREFA_EVENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAREFA_LINK.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TAREFA_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TASK.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TASK_COMENT.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TASK_HIST.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_APONTAM.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_APONTAM_JOB.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_DOC_NF.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_FINANCEIRO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_JOB.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_MILESTONE.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_OS.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_PECA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_PRODUTO_PRECO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TIPO_TAREFA.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_TS_GRUPO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_UNIDADE_NEGOCIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_USUARIO_CARGO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_USUARIO_PAINEL.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_VERSAO.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_VOLUME.sql
@C:\projetos\jobone\versionamento_175\Sequences\SEQ_XML_LOG.sql
