--------------------------------------------------------
--  DDL for Table APONTAM_HORA
--------------------------------------------------------

  CREATE TABLE "APONTAM_HORA" 
   (	"APONTAM_HORA_ID" NUMBER(20,0), 
	"APONTAM_DATA_ID" NUMBER(20,0), 
	"TIPO_APONTAM_ID" NUMBER(20,0), 
	"JOB_ID" NUMBER(20,0), 
	"CLIENTE_ID" NUMBER(20,0), 
	"PAPEL_ID" NUMBER(20,0), 
	"AREA_PAPEL_ID" NUMBER(20,0), 
	"ORDEM_SERVICO_ID" NUMBER(20,0), 
	"PRODUTO_CLIENTE_ID" NUMBER(20,0), 
	"TAREFA_ID" NUMBER(20,0), 
	"OPORTUNIDADE_ID" NUMBER(20,0), 
	"USUARIO_ACAO_ID" NUMBER(20,0), 
	"HORAS" NUMBER(5,2), 
	"HORAS_AJUSTADAS" NUMBER(5,2), 
	"CUSTO" NUMBER(32,2), 
	"VENDA" NUMBER(32,2), 
	"OBS" VARCHAR2(500 CHAR), 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"STATUS" VARCHAR2(10 CHAR), 
	"DATA_ACAO" DATE, 
	"COMENT_ACAO" VARCHAR2(500 CHAR), 
	"UNID_NEG_CLI_ID" NUMBER(20,0), 
	"UNID_NEG_JOB_ID" NUMBER(20,0), 
	"UNID_NEG_USU_ID" NUMBER(20,0), 
	"CONTRATO_ID" NUMBER(20,0), 
	"NUM_REFACAO" NUMBER(5,0)
   ) ;
