--------------------------------------------------------
--  DDL for Table CENARIO_SERVICO_ITEM
--------------------------------------------------------

  CREATE TABLE "CENARIO_SERVICO_ITEM" 
   (	"CENARIO_SERVICO_ITEM_ID" NUMBER(20,0), 
	"CENARIO_SERVICO_ID" NUMBER(20,0), 
	"TIPO_PRODUTO_ID" NUMBER(20,0), 
	"FORNECEDOR_ID" NUMBER(20,0), 
	"COMPLEMENTO" VARCHAR2(500 CHAR), 
	"CUSTO_UNITARIO" NUMBER(25,5), 
	"QUANTIDADE" NUMBER(10,2), 
	"UNIDADE_FREQ" VARCHAR2(20 CHAR), 
	"FREQUENCIA" NUMBER(10,2), 
	"CUSTO_TOTAL" NUMBER(22,2), 
	"HONORARIOS" NUMBER(22,2), 
	"TAXAS" NUMBER(22,2), 
	"PRECO_VENDA" NUMBER(22,2), 
	"PRECO_FINAL" NUMBER(22,2), 
	"MOD_CONTR" VARCHAR2(50 CHAR), 
	"HONORARIO" NUMBER(20,6) DEFAULT 0, 
	"TAXA" NUMBER(20,6) DEFAULT 0
   ) ;
