--------------------------------------------------------
--  DDL for Table CENARIO
--------------------------------------------------------

  CREATE TABLE "CENARIO" 
   (	"CENARIO_ID" NUMBER(20,0), 
	"OPORTUNIDADE_ID" NUMBER(20,0), 
	"NUM_CENARIO" NUMBER(5,0), 
	"NOME" VARCHAR2(100 CHAR), 
	"DATA_ENTRADA" DATE, 
	"NUM_PARCELAS" NUMBER(10,0), 
	"COMENT_PARCELAS" VARCHAR2(2000 CHAR), 
	"FLAG_PADRAO" CHAR(1 CHAR) DEFAULT 'N', 
	"MOEDA" VARCHAR2(10 CHAR), 
	"VALOR_COTACAO" NUMBER(20,6), 
	"DATA_COTACAO" DATE, 
	"PRECO_ID" NUMBER(20,0), 
	"BRIEFING" CLOB, 
	"FLAG_COMISSAO_VENDA" CHAR(1 CHAR), 
	"DATA_PRAZO" DATE, 
	"STATUS" VARCHAR2(20 CHAR), 
	"VALOR" NUMBER(22,2), 
	"STATUS_MARGEM" VARCHAR2(35 CHAR), 
	"APROV_RC_USUARIO_ID" NUMBER(20,0), 
	"DATA_APROV_RC" DATE, 
	"PRAZO_PAGAMENTO" NUMBER(4,0), 
	"PERC_IMPOSTO_PRECIF" NUMBER(7,3), 
	"DATA_PRAZO_APROV" DATE, 
	"COND_PAGAMENTO" NUMBER(3,0), 
	"STATUS_APROV_RC" VARCHAR2(10), 
	"DATA_PRAZO_APROV_RC" DATE, 
	"USUARIO_APROV_RC_ID" NUMBER(20,0), 
	"COMPLEMENTO" VARCHAR2(1000 CHAR), 
	"USU_ALT_ID" NUMBER(20,0), 
	"DATA_ALT" DATE, 
	"MOTIVO" VARCHAR2(2000 CHAR), 
	"PERC_IMPOSTO_HONOR" NUMBER(7,3) DEFAULT 20, 
	"PERC_OVERHEAD" NUMBER(7,3)
   ) ;
