--------------------------------------------------------
--  DDL for Table CENARIO_MOD_CONTR
--------------------------------------------------------

  CREATE TABLE "CENARIO_MOD_CONTR" 
   (	"CENARIO_MOD_CONTR_ID" NUMBER(20,0), 
	"CENARIO_ID" NUMBER(20,0), 
	"ORDEM" NUMBER(3,0), 
	"CODIGO" VARCHAR2(60 CHAR), 
	"DESCRICAO" VARCHAR2(500 CHAR), 
	"FLAG_MARGEM" CHAR(1 CHAR), 
	"FLAG_HONOR" CHAR(1 CHAR), 
	"FLAG_ENCARGO" CHAR(1 CHAR), 
	"FLAG_IMPOSTO" CHAR(1 CHAR), 
	"TIPO_ITEM_CODIGO" VARCHAR2(50 CHAR), 
	"CONTRATO_ID" NUMBER(20,0), 
	"FLAG_IMPO_SO_HONOR" CHAR(1 CHAR) DEFAULT 'N', 
	"TIPO_IMPO_HONOR" VARCHAR2(10) DEFAULT 'NORMAL'
   ) ;
