--------------------------------------------------------
--  DDL for Table COMUNICADO
--------------------------------------------------------

  CREATE TABLE "COMUNICADO" 
   (	"COMUNICADO_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"TIPO_COMUNICADO" VARCHAR2(50 CHAR), 
	"TITULO" VARCHAR2(80 CHAR), 
	"CONTEUDO" CLOB, 
	"URL" VARCHAR2(500 CHAR), 
	"TEXTO_BOTAO" VARCHAR2(20 CHAR), 
	"ILUSTRACAO" VARCHAR2(500 CHAR), 
	"ARQUIVO_ID" NUMBER(20,0), 
	"STATUS" VARCHAR2(20 CHAR), 
	"USUARIO_AUTOR_ID" NUMBER(20,0), 
	"USUARIO_SESSAO_ID" NUMBER(20,0), 
	"DATA_CRIACAO" DATE, 
	"FLAG_LIDO_POR_TODOS" VARCHAR2(1 CHAR)
   ) ;
