--------------------------------------------------------
--  DDL for Table COTACAO_PESSOA_VERSAO
--------------------------------------------------------

  CREATE TABLE "COTACAO_PESSOA_VERSAO" 
   (	"COTACAO_PESSOA_VERSAO_ID" NUMBER(20,0), 
	"COTACAO_PESSOA_ID" NUMBER(20,0), 
	"VERSAO" NUMBER(5,0), 
	"FLAG_PADRAO" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_ESCOLHIDO" CHAR(1 CHAR) DEFAULT 'N', 
	"STATUS_VERSAO" VARCHAR2(10 CHAR) DEFAULT 'PREP', 
	"DATA_PRAZO" DATE, 
	"DETALHES" VARCHAR2(200 CHAR), 
	"DATA_VALIDADE" DATE, 
	"PERC_BV" NUMBER(8,5), 
	"CONDICAO_PAGTO_ID" NUMBER(20,0), 
	"AVALIACAO" VARCHAR2(200 CHAR), 
	"FLAG_VERIF" CHAR(1 CHAR) DEFAULT 'N', 
	"USUARIO_VERIF_ID" NUMBER(20,0), 
	"DATA_VERIF" DATE, 
	"USUARIO_ENVIO_ID" NUMBER(20,0), 
	"DATA_ENVIO" DATE
   ) ;
