--------------------------------------------------------
--  DDL for Table COTACAO_PESSOA
--------------------------------------------------------

  CREATE TABLE "COTACAO_PESSOA" 
   (	"COTACAO_PESSOA_ID" NUMBER(20,0), 
	"COTACAO_ID" NUMBER(20,0), 
	"PESSOA_ID" NUMBER(20,0), 
	"CONTATO_ID" NUMBER(20,0), 
	"INFO_ADICIONAIS" VARCHAR2(500 CHAR), 
	"FLAG_PREFERENCIA" CHAR(1 CHAR) DEFAULT 'N', 
	"DESCR_PREFERENCIA" VARCHAR2(200 CHAR), 
	"USUARIO_PREFERENCIA_ID" NUMBER(20,0), 
	"DATA_PREFERENCIA" DATE, 
	"FLAG_PREF_JOBONEAI" CHAR(1 CHAR) DEFAULT 'N', 
	"DESCR_PREF_JOBONEAI" VARCHAR2(200 CHAR), 
	"DATA_PREF_JOBONEAI" DATE
   ) ;
