--------------------------------------------------------
--  DDL for Table FATURAMENTO_CTR
--------------------------------------------------------

  CREATE TABLE "FATURAMENTO_CTR" 
   (	"FATURAMENTO_CTR_ID" NUMBER(20,0), 
	"CONTRATO_ID" NUMBER(20,0), 
	"EMP_FATURAR_POR_ID" NUMBER(20,0), 
	"CLIENTE_ID" NUMBER(20,0), 
	"CONTATO_CLI_ID" NUMBER(20,0), 
	"NOTA_FISCAL_SAI_ID" NUMBER(20,0), 
	"USUARIO_FATUR_ID" NUMBER(20,0), 
	"DATA_ORDEM" DATE, 
	"DATA_VENCIM" DATE, 
	"DESCRICAO" VARCHAR2(4000 CHAR), 
	"OBS" VARCHAR2(1000 CHAR), 
	"COD_NATUREZA_OPER" VARCHAR2(20 CHAR), 
	"COD_EXT_FATUR" VARCHAR2(20 CHAR), 
	"FLAG_PATROCINIO" CHAR(1 CHAR), 
	"TIPO_RECEITA" VARCHAR2(10 CHAR), 
	"UF_SERVICO" VARCHAR2(2 CHAR), 
	"MUNICIPIO_SERVICO" VARCHAR2(60 CHAR), 
	"ORDEM_COMPRA" VARCHAR2(60 CHAR)
   ) ;
