--------------------------------------------------------
--  DDL for Table FI_TIPO_IMPOSTO
--------------------------------------------------------

  CREATE TABLE "FI_TIPO_IMPOSTO" 
   (	"FI_TIPO_IMPOSTO_ID" NUMBER(20,0), 
	"COD_IMPOSTO" VARCHAR2(20 CHAR), 
	"DESC_IMPOSTO" VARCHAR2(60 CHAR), 
	"PERC_PADRAO" NUMBER(5,2), 
	"PERC_ALTERN1" NUMBER(5,2), 
	"VALOR_FAIXA_RETENCAO" NUMBER(22,2), 
	"VALOR_MINIMO" NUMBER(22,2), 
	"VALOR_MAXIMO" NUMBER(22,2), 
	"COD_RETENCAO_PADRAO" VARCHAR2(10 CHAR), 
	"COD_RETENCAO_ALTERN1" VARCHAR2(10 CHAR), 
	"ORDEM" NUMBER(5,0), 
	"FLAG_INCIDE_ENT" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_INCIDE_SAI" CHAR(1 CHAR) DEFAULT 'S'
   ) ;
