--------------------------------------------------------
--  Arquivo criado - quarta-feira-agosto-20-2025   
--------------------------------------------------------
@C:\projetos\jobone\versionamento_175\Tables\ABATIMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\ABATIMENTO_CTR.sql
@C:\projetos\jobone\versionamento_175\Tables\ADIANT_DESP.sql
@C:\projetos\jobone\versionamento_175\Tables\ADIANT_REALIZ.sql
@C:\projetos\jobone\versionamento_175\Tables\ADNNET_IN.sql
@C:\projetos\jobone\versionamento_175\Tables\ADNNET_OUT.sql
@C:\projetos\jobone\versionamento_175\Tables\AJUSTE_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_DATA.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_DATA_EV.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_ENCE.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_HORA.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_OPORT.sql
@C:\projetos\jobone\versionamento_175\Tables\APONTAM_PROGR.sql
@C:\projetos\jobone\versionamento_175\Tables\AREA.sql
@C:\projetos\jobone\versionamento_175\Tables\AREA_DICION_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_CARTA.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_CENARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_COMUNICADO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_CONTRATO_FISICO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_EMPRESA.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_NF.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_OPORTUNIDADE.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_ORCAMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_OS.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_TAREFA.sql
@C:\projetos\jobone\versionamento_175\Tables\ARQUIVO_TASK.sql
@C:\projetos\jobone\versionamento_175\Tables\AVAL_FORNEC.sql
@C:\projetos\jobone\versionamento_175\Tables\BKP_CATEGORIA.sql
@C:\projetos\jobone\versionamento_175\Tables\BKP_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\BRIEF_AREA.sql
@C:\projetos\jobone\versionamento_175\Tables\BRIEF_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\BRIEF_DICION_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\BRIEF_HIST.sql
@C:\projetos\jobone\versionamento_175\Tables\BRIEFING.sql
@C:\projetos\jobone\versionamento_175\Tables\CAMPANHA.sql
@C:\projetos\jobone\versionamento_175\Tables\CARGO.sql
@C:\projetos\jobone\versionamento_175\Tables\CARTA_ACORDO.sql
@C:\projetos\jobone\versionamento_175\Tables\CARTA_FLUXO_APROV.sql
@C:\projetos\jobone\versionamento_175\Tables\CATEGORIA.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO_EMPRESA.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO_MOD_CONTR.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO_SERVICO_HORAS.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO_SERVICO_ITEM.sql
@C:\projetos\jobone\versionamento_175\Tables\CENARIO_SERVICO_USU.sql
@C:\projetos\jobone\versionamento_175\Tables\CEP.sql
@C:\projetos\jobone\versionamento_175\Tables\CLASSE_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\COMENTARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\COMENT_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\COMISSAO.sql
@C:\projetos\jobone\versionamento_175\Tables\COMUNICADO.sql
@C:\projetos\jobone\versionamento_175\Tables\COMUNICADO_PAPEL.sql
@C:\projetos\jobone\versionamento_175\Tables\COMUNICADO_USU.sql
@C:\projetos\jobone\versionamento_175\Tables\CONDICAO_PAGTO.sql
@C:\projetos\jobone\versionamento_175\Tables\CONDICAO_PAGTO_DET.sql
@C:\projetos\jobone\versionamento_175\Tables\CONDICAO_PAGTO_DIA.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTEXTO_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_ELAB.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_FISICO.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_HORAS.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_HORAS_USU.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_ITEM.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_NITEM_PDR.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_SERV_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\CONTRATO_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO_ITEM.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO_PESSOA_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO_PESSOA_ITEM.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO_PESSOA_LINK.sql
@C:\projetos\jobone\versionamento_175\Tables\COTACAO_PESSOA_VERSAO.sql
@C:\projetos\jobone\versionamento_175\Tables\CRONOGRAMA.sql
@C:\projetos\jobone\versionamento_175\Tables\CT_TRANSICAO.sql
@C:\projetos\jobone\versionamento_175\Tables\CTX_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\DEPARTAMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\DESP_REALIZ.sql
@C:\projetos\jobone\versionamento_175\Tables\DEVOL_REALIZ.sql
@C:\projetos\jobone\versionamento_175\Tables\DIA_ALOCACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\DIA_SEMANA.sql
@C:\projetos\jobone\versionamento_175\Tables\DICIONARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\DICIONARIO_TIPO.sql
@C:\projetos\jobone\versionamento_175\Tables\DICION_EMP.sql
@C:\projetos\jobone\versionamento_175\Tables\DICION_EMP_VAL.sql
@C:\projetos\jobone\versionamento_175\Tables\DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\DUPLICATA.sql
@C:\projetos\jobone\versionamento_175\Tables\EMAIL_CARTA.sql
@C:\projetos\jobone\versionamento_175\Tables\EMPRESA.sql
@C:\projetos\jobone\versionamento_175\Tables\EMPRESA_PARAMETRO.sql
@C:\projetos\jobone\versionamento_175\Tables\EMPRESA_SIST_EXT.sql
@C:\projetos\jobone\versionamento_175\Tables\EMPR_FATUR_SIST_EXT.sql
@C:\projetos\jobone\versionamento_175\Tables\EMPR_RESP_SIST_EXT.sql
@C:\projetos\jobone\versionamento_175\Tables\EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Tables\EQUIPE_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\ERRO_LOG.sql
@C:\projetos\jobone\versionamento_175\Tables\EVENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\EVENTO_CONFIG.sql
@C:\projetos\jobone\versionamento_175\Tables\EVENTO_MOTIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\FAIXA_APROV.sql
@C:\projetos\jobone\versionamento_175\Tables\FAIXA_APROV_AO.sql
@C:\projetos\jobone\versionamento_175\Tables\FAIXA_APROV_OS.sql
@C:\projetos\jobone\versionamento_175\Tables\FAIXA_APROV_PAPEL.sql
@C:\projetos\jobone\versionamento_175\Tables\FATURAMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\FATURAMENTO_CTR.sql
@C:\projetos\jobone\versionamento_175\Tables\FERIADO.sql
@C:\projetos\jobone\versionamento_175\Tables\FI_BANCO.sql
@C:\projetos\jobone\versionamento_175\Tables\FI_TIPO_IMPOSTO.sql
@C:\projetos\jobone\versionamento_175\Tables\FI_TIPO_IMPOSTO_FAIXA.sql
@C:\projetos\jobone\versionamento_175\Tables\FI_TIPO_IMPOSTO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\FREQUENCIA.sql
@C:\projetos\jobone\versionamento_175\Tables\GRUPO.sql
@C:\projetos\jobone\versionamento_175\Tables\GRUPO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\GRUPO_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\HIST_ENDER.sql
@C:\projetos\jobone\versionamento_175\Tables\HISTORICO.sql
@C:\projetos\jobone\versionamento_175\Tables\HIST_SENHA.sql
@C:\projetos\jobone\versionamento_175\Tables\IMPOSTO_NOTA.sql
@C:\projetos\jobone\versionamento_175\Tables\INTERACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_ABAT.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_ADIANT.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_CARTA.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_CRONO_DEST.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_CRONO_DIA.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_CRONO_PRE.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_CRONO_USU.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_DECUP.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_FATUR.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_HIST.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_NOTA.sql
@C:\projetos\jobone\versionamento_175\Tables\ITEM_SOBRA.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB_HORAS.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB_NITEM_PDR.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB_PECA.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB_RECEITA_CTR.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\JOB_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\LANCAMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\LINK_DIRETO.sql
@C:\projetos\jobone\versionamento_175\Tables\MARK.sql
@C:\projetos\jobone\versionamento_175\Tables\METADADO.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_CARGA.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_CARGA_DESCARTE.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_CRIT_SEC.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_DAYPART.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_DAYPART_VAR.sql
@C:\projetos\jobone\versionamento_175\Tables\MILESTONE.sql
@C:\projetos\jobone\versionamento_175\Tables\MILESTONE_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_METAS_DIGITAL.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_METAS_OOH.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_METAS_PRINT.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_METAS_RADIO.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_METAS_TV.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_PI.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_PI_DESCARTE.sql
@C:\projetos\jobone\versionamento_175\Tables\MI_VERSAO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__AREA.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__ARQUIVO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__CARGO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__CRONOGRAMA.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__DICIONARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__GRUPO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__GRUPO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__ITEM_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__JOB_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__METADADO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__MV_NEGOCIACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__ORDEM_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__OS_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__OS_NEGOCIACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__OS_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__PRODUTO_CLIENTE.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__TAREFA.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__TIPO_OS.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__USUARIO_CARGO.sql
@C:\projetos\jobone\versionamento_175\Tables\MLOG__VOLUME.sql
@C:\projetos\jobone\versionamento_175\Tables\MODAL_CONTRATACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\MOD_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\MOD_ITEM_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\MOD_ITEM_CRONO_DEST.sql
@C:\projetos\jobone\versionamento_175\Tables\MOD_ITEM_CRONO_DIA.sql
@C:\projetos\jobone\versionamento_175\Tables\MOD_ITEM_CRONO_PRE.sql
@C:\projetos\jobone\versionamento_175\Tables\NATUREZA_ITEM.sql
@C:\projetos\jobone\versionamento_175\Tables\NATUREZA_ITEM_INC.sql
@C:\projetos\jobone\versionamento_175\Tables\NATUREZA_OPER_FATUR.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTA_FISCAL.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTA_FISCAL_PAGTO.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_CONFIG.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_DESLIGA.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_FILA.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_FILA_EMAIL.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_FILA_USU.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_PAPEL.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\NOTIFICA_USU_AVULSO.sql
@C:\projetos\jobone\versionamento_175\Tables\NUMERO_OS.sql
@C:\projetos\jobone\versionamento_175\Tables\OBJETO_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\OPORT_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Tables\OPORT_POTENCIAL.sql
@C:\projetos\jobone\versionamento_175\Tables\OPORT_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\OPORTUNIDADE.sql
@C:\projetos\jobone\versionamento_175\Tables\OPORT_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\ORCAMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\ORCAM_FLUXO_APROV.sql
@C:\projetos\jobone\versionamento_175\Tables\ORCAM_NITEM_PDR.sql
@C:\projetos\jobone\versionamento_175\Tables\ORCAM_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\ORDEM_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_AFAZER.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_ESTIM.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_EVENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_FLUXO_APROV.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_HORAS.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_LINK.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_NEGOCIACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_REFACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_TIPO_PRODUTO_REF.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_TP_ATRIBUTO_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_TRANSICAO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_USUARIO_DATA.sql
@C:\projetos\jobone\versionamento_175\Tables\OS_USUARIO_REFACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\PADRAO_PLANILHA.sql
@C:\projetos\jobone\versionamento_175\Tables\PAINEL.sql
@C:\projetos\jobone\versionamento_175\Tables\PAIS.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PAINEL.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV_AREA.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV_TDOC.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV_TFIN.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV_TJOB.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV_TOS.sql
@C:\projetos\jobone\versionamento_175\Tables\PAPEL_PRIV_TPESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\PARAMETRO.sql
@C:\projetos\jobone\versionamento_175\Tables\PARCELA.sql
@C:\projetos\jobone\versionamento_175\Tables\PARCELA_CARTA.sql
@C:\projetos\jobone\versionamento_175\Tables\PARCELA_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Tables\PARCELA_FATUR_CTR.sql
@C:\projetos\jobone\versionamento_175\Tables\PARCELA_NF.sql
@C:\projetos\jobone\versionamento_175\Tables\PESQUISA.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_HOMOLOG.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_LINK.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_NITEM_PDR.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_SIST_EXT.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\PESSOA_TRANSFERENCIA.sql
@C:\projetos\jobone\versionamento_175\Tables\PLSQL_PROFILER_DATA.sql
@C:\projetos\jobone\versionamento_175\Tables\PLSQL_PROFILER_RUNS.sql
@C:\projetos\jobone\versionamento_175\Tables\PLSQL_PROFILER_UNITS.sql
@C:\projetos\jobone\versionamento_175\Tables\PONTO_INTEGRACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\PREFERENCIA.sql
@C:\projetos\jobone\versionamento_175\Tables\PRIVILEGIO.sql
@C:\projetos\jobone\versionamento_175\Tables\PRODUTO_CLIENTE.sql
@C:\projetos\jobone\versionamento_175\Tables\PRODUTO_FISCAL.sql
@C:\projetos\jobone\versionamento_175\Tables\QUADRO.sql
@C:\projetos\jobone\versionamento_175\Tables\QUADRO_COLUNA.sql
@C:\projetos\jobone\versionamento_175\Tables\QUADRO_EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Tables\QUADRO_OS_CONFIG.sql
@C:\projetos\jobone\versionamento_175\Tables\QUADRO_TAREFA_CONFIG.sql
@C:\projetos\jobone\versionamento_175\Tables\REGRA_COENDER.sql
@C:\projetos\jobone\versionamento_175\Tables\RELACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\REL_APON_MENS_COL.sql
@C:\projetos\jobone\versionamento_175\Tables\REL_APON_MENS_LIN.sql
@C:\projetos\jobone\versionamento_175\Tables\REL_APON_MENS_VAL.sql
@C:\projetos\jobone\versionamento_175\Tables\REL_FLUXO_CHECKIN.sql
@C:\projetos\jobone\versionamento_175\Tables\REL_OS_TLINE.sql
@C:\projetos\jobone\versionamento_175\Tables\REL_RENTAB_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\SA_EMP_RESP.sql
@C:\projetos\jobone\versionamento_175\Tables\SALARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\SALARIO_CARGO.sql
@C:\projetos\jobone\versionamento_175\Tables\SALARIO_CARGO_BKP_121223.sql
@C:\projetos\jobone\versionamento_175\Tables\SERVICO.sql
@C:\projetos\jobone\versionamento_175\Tables\SERVIDOR_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\SETOR.sql
@C:\projetos\jobone\versionamento_175\Tables\SISTEMA_EXTERNO.sql
@C:\projetos\jobone\versionamento_175\Tables\SIST_EXT_PARAMETRO.sql
@C:\projetos\jobone\versionamento_175\Tables\SIST_EXT_PONTO_INT.sql
@C:\projetos\jobone\versionamento_175\Tables\SOBRA.sql
@C:\projetos\jobone\versionamento_175\Tables\SOLICIT_ADIANT.sql
@C:\projetos\jobone\versionamento_175\Tables\SQLN_EXPLAIN_PLAN.sql
@C:\projetos\jobone\versionamento_175\Tables\STATUS_AUX_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\STATUS_AUX_OPORT.sql
@C:\projetos\jobone\versionamento_175\Tables\TAB_FERIADO.sql
@C:\projetos\jobone\versionamento_175\Tables\TAB_PRECO.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_AFAZER.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_EVENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_LINK.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_TP_ATRIB_VALOR.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\TAREFA_USUARIO_DATA.sql
@C:\projetos\jobone\versionamento_175\Tables\TASK.sql
@C:\projetos\jobone\versionamento_175\Tables\TASK_COMENT.sql
@C:\projetos\jobone\versionamento_175\Tables\TASK_HIST.sql
@C:\projetos\jobone\versionamento_175\Tables\TASK_HIST_CIENCIA.sql
@C:\projetos\jobone\versionamento_175\Tables\TAXA_FINANC.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPIFIC_MILESTONE.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPIFIC_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_ACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_APONTAM.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_APONTAM_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_ARQUIVO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_CONTRATO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_DADO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_DOC_NF.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_DOCUMENTO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_FINANCEIRO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_INTEGRACAO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_JOB.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_JOB_MOD_CRONO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_JOB_USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_MILESTONE.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_OBJETO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_OS.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_OS_TRANSICAO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PECA.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PESSOA.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PROD_TIPO_OS.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PRODUTO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PRODUTO_PRECO.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PRODUTO_TRANSF.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_PRODUTO_VAR.sql
@C:\projetos\jobone\versionamento_175\Tables\TIPO_TAREFA.sql
@C:\projetos\jobone\versionamento_175\Tables\TS_APROVADOR.sql
@C:\projetos\jobone\versionamento_175\Tables\TS_EQUIPE.sql
@C:\projetos\jobone\versionamento_175\Tables\TS_GRUPO.sql
@C:\projetos\jobone\versionamento_175\Tables\TS_TRANSICAO.sql
@C:\projetos\jobone\versionamento_175\Tables\UNIDADE_NEGOCIO.sql
@C:\projetos\jobone\versionamento_175\Tables\UNIDADE_NEGOCIO_CLI.sql
@C:\projetos\jobone\versionamento_175\Tables\UNIDADE_NEGOCIO_USU.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_CARGO.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_COENDER.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_EMPRESA.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_ENDER.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_PAPEL.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_PREF.sql
@C:\projetos\jobone\versionamento_175\Tables\USUARIO_TRANSF.sql
@C:\projetos\jobone\versionamento_175\Tables\VERSAO.sql
@C:\projetos\jobone\versionamento_175\Tables\VOLUME.sql
@C:\projetos\jobone\versionamento_175\Tables\XML_LOG.sql
