--------------------------------------------------------
--  DDL for Table IMPOSTO_NOTA
--------------------------------------------------------

  CREATE TABLE "IMPOSTO_NOTA" 
   (	"IMPOSTO_NOTA_ID" NUMBER(20,0), 
	"NOTA_FISCAL_ID" NUMBER(20,0), 
	"FI_TIPO_IMPOSTO_ID" NUMBER(20,0), 
	"NUM_SEQ" NUMBER(4,0), 
	"VALOR_TRIBUTADO" NUMBER(22,2), 
	"VALOR_BASE_CALC" NUMBER(22,2), 
	"PERC_IMPOSTO_SUGERIDO" NUMBER(5,2), 
	"PERC_IMPOSTO_NOTA" NUMBER(22,2), 
	"VALOR_DEDUCAO" NUMBER(22,2) DEFAULT 0, 
	"VALOR_IMPOSTO_BASE" NUMBER(22,2), 
	"VALOR_IMPOSTO_ACUM" NUMBER(22,2), 
	"VALOR_IMPOSTO" NUMBER(22,2), 
	"COD_RETENCAO" VARCHAR2(5 CHAR), 
	"FLAG_RETER" CHAR(1 CHAR)
   ) ;
