--------------------------------------------------------
--  DDL for Table MARK
--------------------------------------------------------

  CREATE TABLE "MARK" 
   (	"ID" VARCHAR2(255 CHAR), 
	"ORDEM_SERVICO_ID" NUMBER(20,0), 
	"ARQUIVO_ID" NUMBER(20,0), 
	"STATUS_OS" VARCHAR2(20 CHAR), 
	"REFACAO" NUMBER(20,0), 
	"DOCUMENT_FILENAME" VARCHAR2(255 CHAR), 
	"DOCUMENT_RELATIVE_PATH" VARCHAR2(255 CHAR), 
	"SELECTION_TEXT" CLOB, 
	"HAS_SELECTION" NUMBER(11,0), 
	"COLOR" VARCHAR2(7 CHAR), 
	"SELECTION_INFO" VARCHAR2(30 CHAR), 
	"READONLY" NUMBER(1,0), 
	"TYPE" VARCHAR2(30 CHAR), 
	"DISPLAYFORMAT" VARCHAR2(30 CHAR), 
	"NOTE" CLOB, 
	"PAGEINDEX" NUMBER(11,0), 
	"POSITIONX" NUMBER, 
	"POSITIONY" NUMBER, 
	"WIDTH" NUMBER(11,0), 
	"HEIGHT" NUMBER(11,0), 
	"COLLAPSED" NUMBER(1,0), 
	"POINTS" CLOB, 
	"DATECREATED" DATE, 
	"DATECHANGED" DATE, 
	"AUTHOR" VARCHAR2(30 CHAR)
   ) ;
