--------------------------------------------------------
--  DDL for Table METADADO
--------------------------------------------------------

  CREATE TABLE "METADADO" 
   (	"METADADO_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"TIPO_DADO_ID" NUMBER(20,0), 
	"METADADO_COND_ID" NUMBER(20,0), 
	"TIPO_OBJETO" VARCHAR2(20 CHAR), 
	"OBJETO_ID" NUMBER(20,0), 
	"GRUPO" VARCHAR2(20 CHAR), 
	"NOME" VARCHAR2(250 CHAR), 
	"TAMANHO" NUMBER(5,0), 
	"FLAG_OBRIGATORIO" CHAR(1 CHAR), 
	"SUFIXO" VARCHAR2(20 CHAR), 
	"INSTRUCOES" VARCHAR2(500 CHAR), 
	"VALORES" VARCHAR2(4000 CHAR), 
	"ORDEM" NUMBER(5,0), 
	"FLAG_ATIVO" CHAR(1 CHAR), 
	"FLAG_AO_LADO" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_NA_LISTA" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_ORDENAR" CHAR(1 CHAR) DEFAULT 'N', 
	"VALOR_COND" VARCHAR2(500 CHAR), 
	"PRIVILEGIO_ID" NUMBER(20,0)
   ) ;
