--------------------------------------------------------
--  DDL for Table MI_METAS_RADIO
--------------------------------------------------------

  CREATE TABLE "MI_METAS_RADIO" 
   (	"MI_METAS_RADIO_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"ANO" NUMBER(10,0), 
	"DATA_CARGA" DATE, 
	"VEICULO" VARCHAR2(100 CHAR), 
	"PRACA" VARCHAR2(100 CHAR), 
	"FORMATO" VARCHAR2(100 CHAR), 
	"VALOR_UNIT_NEG" NUMBER(25,4) DEFAULT 0, 
	"VALOR_UNIT_NEG_REAL" NUMBER(25,4) DEFAULT 0, 
	"FLAG_SEM_META" CHAR(1 CHAR), 
	"MI_DAYPART_ID" NUMBER(20,0), 
	"DAYPART" VARCHAR2(100 CHAR), 
	"VALOR_UNIT_NEG_Q1_REAL" NUMBER(25,4) DEFAULT 0, 
	"VALOR_UNIT_NEG_Q2_REAL" NUMBER(25,4) DEFAULT 0, 
	"VALOR_UNIT_NEG_Q3_REAL" NUMBER(25,4) DEFAULT 0, 
	"VALOR_UNIT_NEG_Q4_REAL" NUMBER(25,4) DEFAULT 0, 
	"MI_CARGA_ID" NUMBER(20,0), 
	"FLAG_BONIFICACAO" CHAR(1 CHAR) DEFAULT 'N', 
	"VALOR_ABS_NEG_Q1_REAL" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q2_REAL" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q3_REAL" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q4_REAL" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q1_META" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q2_META" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q3_META" NUMBER(25,4), 
	"VALOR_ABS_NEG_Q4_META" NUMBER(25,4)
   ) ;
