--------------------------------------------------------
--  DDL for Table NOTA_FISCAL_PAGTO
--------------------------------------------------------

  CREATE TABLE "NOTA_FISCAL_PAGTO" 
   (	"NOTA_FISCAL_PAGTO_ID" NUMBER(20,0), 
	"NOTA_FISCAL_ID" NUMBER(20,0), 
	"SEQUENCIA" NUMBER(20,0), 
	"ACAO" CHAR(1), 
	"TIPO_BAIXA" CHAR(1), 
	"DATA_BAIXA" DATE, 
	"VALOR_LIQUIDO" NUMBER(22,2) DEFAULT 0, 
	"VALOR_DESCONTO" NUMBER(22,2) DEFAULT 0, 
	"VALOR_JUROS" NUMBER(22,2) DEFAULT 0, 
	"VALOR_MULTA" NUMBER(22,2) DEFAULT 0, 
	"SALDO_LIQUIDO" NUMBER(22,2) DEFAULT 0, 
	"SALDO_BRUTO" NUMBER(22,2) DEFAULT 0, 
	"USUARIO_ID" NUMBER(20,0), 
	"DATA_LANCAMENTO" DATE
   ) ;
