--------------------------------------------------------
--  DDL for Table NOTIFICA_CONFIG
--------------------------------------------------------

  CREATE TABLE "NOTIFICA_CONFIG" 
   (	"NOTIFICA_CONFIG_ID" NUMBER(20,0), 
	"EVENTO_CONFIG_ID" NUMBER(20,0), 
	"TIPO_NOTIFIC" VARCHAR2(5 CHAR), 
	"FLAG_ENDER_TODOS" CHAR(1 CHAR), 
	"FLAG_ENDER_PAPEL" CHAR(1 CHAR), 
	"FLAG_USU_PAPEL" CHAR(1 CHAR), 
	"FLAG_USU_INDICADO" CHAR(1 CHAR), 
	"FLAG_JOB_CRIADOR" CHAR(1 CHAR), 
	"FLAG_JOB_RESPINT" CHAR(1 CHAR), 
	"FLAG_OS_SOLICIT" CHAR(1 CHAR), 
	"FLAG_OS_DISTR" CHAR(1 CHAR), 
	"FLAG_OS_EXEC" CHAR(1 CHAR), 
	"FLAG_OS_APROV" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_CA_PRODUTOR" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_CTR_CRIADOR" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_CTR_RESPINT" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_AD_CRIADOR" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_AD_SOLICIT" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_AD_APROV" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_EST_CRIADOR" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_EST_APROV" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_DOC_CRIADOR" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_DOC_APROV" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_BRI_APROV" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_PA_NOTIF_ENDER" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_EMAILS" CHAR(1 CHAR), 
	"EMAILS" VARCHAR2(500 CHAR)
   ) ;
