--------------------------------------------------------
--  DDL for Table OPORTUNIDADE
--------------------------------------------------------

  CREATE TABLE "OPORTUNIDADE" 
   (	"OPORTUNIDADE_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"CLIENTE_ID" NUMBER(20,0), 
	"CONTATO_ID" NUMBER(20,0), 
	"PRODUTO_CLIENTE_ID" NUMBER(20,0), 
	"STATUS_AUX_OPORT_ID" NUMBER(20,0), 
	"CLIENTE_CONFLITO_ID" NUMBER(20,0), 
	"USUARIO_SOLIC_ID" NUMBER(20,0), 
	"CENARIO_ESCOLHIDO_ID" NUMBER(20,0), 
	"ARQUIVO_PROP_ID" NUMBER(20,0), 
	"ARQUIVO_PREC_ID" NUMBER(20,0), 
	"TIPO_CONTRATO_ID" NUMBER(20,0), 
	"NUMERO" VARCHAR2(20 CHAR), 
	"NOME" VARCHAR2(120 CHAR), 
	"DATA_ENTRADA" DATE, 
	"ORIGEM" VARCHAR2(5 CHAR), 
	"TIPO_NEGOCIO" VARCHAR2(50 CHAR), 
	"FLAG_CONFLITO" CHAR(1 CHAR), 
	"STATUS" VARCHAR2(10 CHAR), 
	"DATA_STATUS" DATE, 
	"TIPO_CONC" VARCHAR2(10 CHAR), 
	"PERDA_PARA" VARCHAR2(100 CHAR), 
	"MOTIVO_STATUS" VARCHAR2(100 CHAR), 
	"COMPL_STATUS" VARCHAR2(500 CHAR), 
	"VALOR_OPORTUN" NUMBER(22,2), 
	"PERC_PROB_FECH" NUMBER(5,2), 
	"DATA_PROV_FECH" DATE, 
	"DATA_PROX_INT" DATE, 
	"COMPL_ORIGEM" VARCHAR2(200 CHAR), 
	"USUARIO_RESP_ID" NUMBER(20,0), 
	"UNID_NEGOCIO_RESP_ID" NUMBER(20,0), 
	"ARQUIVO_ACEI_ID" NUMBER(20,0), 
	"FLAG_SEM_PRECO_MANUAL" CHAR(1) DEFAULT 'N'
   ) ;
