--------------------------------------------------------
--  DDL for Table ORCAMENTO
--------------------------------------------------------

  CREATE TABLE "ORCAMENTO" 
   (	"ORCAMENTO_ID" NUMBER(20,0), 
	"JOB_ID" NUMBER(20,0), 
	"USUARIO_AUTOR_ID" NUMBER(20,0), 
	"CONTATO_FATUR_ID" NUMBER(20,0), 
	"EMP_FATURAR_POR_ID" NUMBER(20,0), 
	"TIPO_JOB_ID" NUMBER(20,0), 
	"USUARIO_STATUS_ID" NUMBER(20,0), 
	"TIPO_FINANCEIRO_ID" NUMBER(20,0), 
	"NUM_ORCAMENTO" NUMBER(5,0), 
	"DATA_CRIACAO" DATE, 
	"DATA_APROVACAO" DATE, 
	"DESCRICAO" VARCHAR2(4000 CHAR), 
	"DATA_PREV_INI" DATE, 
	"DATA_PREV_FIM" DATE, 
	"MUNICIPIO_SERVICO" VARCHAR2(60 CHAR), 
	"UF_SERVICO" VARCHAR2(2 CHAR), 
	"FLAG_PAGO_CLIENTE" CHAR(1 CHAR) DEFAULT 'N', 
	"OBS_FATUR" VARCHAR2(2000 CHAR), 
	"OBS_CHECKIN" VARCHAR2(2000 CHAR), 
	"DATA_STATUS" DATE, 
	"STATUS" VARCHAR2(20 CHAR), 
	"DATA_PREV_FEC_CHECK" DATE, 
	"MOTIVO_STATUS" VARCHAR2(100 CHAR), 
	"COMPL_STATUS" VARCHAR2(1000 CHAR), 
	"META_VALOR_MIN" NUMBER(22,2), 
	"META_VALOR_MAX" NUMBER(22,2), 
	"DATA_APROV_LIMITE" DATE, 
	"FLAG_COM_APROV" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_DESPESA" CHAR(1 CHAR) DEFAULT 'N', 
	"COD_EXT_ORCAM" VARCHAR2(20 CHAR), 
	"ORDEM_COMPRA" VARCHAR2(60 CHAR), 
	"SERVICO_ID" NUMBER(20,0), 
	"COD_EXTERNO" VARCHAR2(20 CHAR)
   ) ;
