--------------------------------------------------------
--  DDL for Table OS_EVENTO
--------------------------------------------------------

  CREATE TABLE "OS_EVENTO" 
   (	"OS_EVENTO_ID" NUMBER(20,0), 
	"ORDEM_SERVICO_ID" NUMBER(20,0), 
	"USUARIO_ID" NUMBER(20,0), 
	"BRIEFING_ID" NUMBER(20,0), 
	"DATA_EVENTO" DATE, 
	"COD_ACAO" VARCHAR2(20 CHAR), 
	"NUM_REFACAO" NUMBER(5,0), 
	"COMPLEX_REFACAO" VARCHAR2(2 CHAR), 
	"STATUS_DE" VARCHAR2(20 CHAR), 
	"STATUS_PARA" VARCHAR2(20 CHAR), 
	"MOTIVO" VARCHAR2(100 CHAR), 
	"TEXTO_XML" CLOB, 
	"FLAG_RECUSA" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_ESTIM" CHAR(1 CHAR) DEFAULT 'N', 
	"TIPO_CLIENTE_AGENCIA" VARCHAR2(3 CHAR), 
	"COMENTARIO" CLOB
   ) ;
