--------------------------------------------------------
--  DDL for Table OS_REFACAO
--------------------------------------------------------

  CREATE TABLE "OS_REFACAO" 
   (	"ORDEM_SERVICO_ID" NUMBER(20,0), 
	"FLAG_ESTIM" CHAR(1 CHAR) DEFAULT 'N', 
	"NUM_REFACAO" NUMBER(5,0), 
	"DATA_SOLICITADA" DATE, 
	"DATA_INTERNA" DATE, 
	"DATA_ENVIO" DATE, 
	"DATA_TERMINO_EXEC" DATE, 
	"DATA_CONCLUSAO" DATE, 
	"DIAS_PRAZO_INTERNO" NUMBER(5,0), 
	"DIAS_PRAZO_SOLICITADO" NUMBER(5,0), 
	"DIAS_ATRASO_INTERNO" NUMBER(5,0), 
	"DIAS_ATRASO_SOLICITADO" NUMBER(5,0), 
	"DIAS_TERMINO_EXEC" NUMBER(5,0), 
	"DIAS_AVALIACAO" NUMBER(5,0), 
	"DIAS_TOTAIS" NUMBER(5,0), 
	"DATA_ACEITE" DATE, 
	"DATA_DISTR" DATE, 
	"DATA_APROV_EXEC" DATE, 
	"DATA_APROV_CLI" DATE
   ) ;
