--------------------------------------------------------
--  DDL for Table PAINEL
--------------------------------------------------------

  CREATE TABLE "PAINEL" 
   (	"PAINEL_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"NOME" VARCHAR2(100 CHAR), 
	"DESCRICAO" VARCHAR2(4000 CHAR), 
	"AUTORIA" VARCHAR2(100 CHAR), 
	"VERSAO" VARCHAR2(10 CHAR), 
	"DATA_REFER" DATE, 
	"CONTATO" VARCHAR2(100 CHAR), 
	"URL" VARCHAR2(4000 CHAR), 
	"FLAG_PADRAO" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"FLAG_ATIVO" CHAR(1 CHAR) DEFAULT 'S', 
	"ORIGEM" VARCHAR2(10 CHAR), 
	"ABERTURA" VARCHAR2(10 CHAR), 
	"DASH_NUMERO" NUMBER(10,0), 
	"API_KEY" VARCHAR2(1000), 
	"FLAG_USUARIO_ID" CHAR(1 CHAR) DEFAULT 'N'
   ) ;
