--------------------------------------------------------
--  DDL for Table PESSOA_HOMOLOG
--------------------------------------------------------

  CREATE TABLE "PESSOA_HOMOLOG" 
   (	"PESSOA_HOMOLOG_ID" NUMBER(20,0), 
	"PESSOA_ID" NUMBER(20,0), 
	"CONDICAO_PAGTO_ID" NUMBER(20,0), 
	"USUARIO_ID" NUMBER(20,0), 
	"DATA_HORA" DATE, 
	"STATUS_DE" VARCHAR2(10), 
	"STATUS_PARA" VARCHAR2(10), 
	"PERC_BV" NUMBER(8,5), 
	"TIPO_FATUR_BV" VARCHAR2(3 CHAR), 
	"FLAG_TEM_BV" CHAR(1) DEFAULT 'N', 
	"PERC_IMPOSTO" NUMBER(5,2), 
	"FLAG_NOTA_COBERT" CHAR(1) DEFAULT 'S', 
	"DATA_VALIDADE" DATE, 
	"OBS" VARCHAR2(500), 
	"AVAL_AI" VARCHAR2(500), 
	"FLAG_ATUAL" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_TEM_COBERT" CHAR(1)
   ) ;
