--------------------------------------------------------
--  DDL for Table SALARIO_CARGO_BKP_121223
--------------------------------------------------------

  CREATE TABLE "SALARIO_CARGO_BKP_121223" 
   (	"SALARIO_CARGO_ID" NUMBER(20,0), 
	"CARGO_ID" NUMBER(20,0), 
	"PRECO_ID" NUMBER(20,0), 
	"NOME_ALTERNATIVO" VARCHAR2(100 CHAR), 
	"NIVEL" VARCHAR2(5 CHAR), 
	"CUSTO_MENSAL" NUMBER(32,2), 
	"CUSTO_HORA" NUMBER(32,2), 
	"VENDA_MENSAL" NUMBER(32,2), 
	"VENDA_HORA" NUMBER(32,2), 
	"FAIXA_SALARIAL" NUMBER(32,2), 
	"BENEFICIO" NUMBER(32,2), 
	"ENCARGO" NUMBER(32,2), 
	"DISSIDIO" NUMBER(32,2), 
	"OVERHEAD" NUMBER(32,2), 
	"MARGEM_HORA" NUMBER(32,2), 
	"MARGEM_MENSAL" NUMBER(32,2)
   ) ;
