--------------------------------------------------------
--  DDL for Table TAB_PRECO
--------------------------------------------------------

  CREATE TABLE "TAB_PRECO" 
   (	"PRECO_ID" NUMBER(20,0), 
	"CLIENTE_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"GRUPO_ID" NUMBER(20,0), 
	"NOME" VARCHAR2(200 CHAR), 
	"TABELA_PRECO_BASE_ID" NUMBER(20,0), 
	"DATA_REFERENCIA" DATE, 
	"DATA_INI" DATE, 
	"DATA_FIM" DATE, 
	"DATA_VALIDADE" DATE, 
	"FLAG_PODE_PRECIF" CHAR(1 CHAR), 
	"FLAG_PODE_GANHAR" CHAR(1 CHAR), 
	"FLAG_PADRAO_ATUAL" CHAR(1 CHAR), 
	"FLAG_PADRAO" CHAR(1 CHAR), 
	"FLAG_ARQUIVADA" CHAR(1 CHAR), 
	"PERC_ACRES_CARGO" NUMBER(32,5), 
	"PERC_ACRES_TIPO_PROD" NUMBER(32,5), 
	"USU_CRIA_ID" NUMBER(20,0), 
	"DATA_CRIACAO" DATE, 
	"USU_ALT_ID" NUMBER(20,0), 
	"DATA_ULT_ALT" DATE
   ) ;
