--------------------------------------------------------
--  DDL for Table TAREFA
--------------------------------------------------------

  CREATE TABLE "TAREFA" 
   (	"TAREFA_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"USUARIO_DE_ID" NUMBER(20,0), 
	"JOB_ID" NUMBER(20,0), 
	"DESCRICAO" VARCHAR2(1000 CHAR), 
	"DATA_ENTRADA" DATE, 
	"DATA_TERMINO" DATE, 
	"DATA_ENVIO" DATE, 
	"STATUS" VARCHAR2(10 CHAR), 
	"DATA_STATUS" DATE, 
	"DETALHES" CLOB, 
	"DATA_INICIO" DATE, 
	"FLAG_VOLTA_EXEC" CHAR(1 CHAR) DEFAULT 'N', 
	"ORDEM_SERVICO_ID" NUMBER(20,0), 
	"NUMERO" NUMBER(10,0), 
	"FLAG_DEVOLVIDA" CHAR(1 CHAR) DEFAULT 'N', 
	"DATA_EXECUCAO" DATE, 
	"FLAG_DESC_USUARIO" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_OBRIGA_ITEM" CHAR(1 CHAR) DEFAULT 'N', 
	"NUM_MAX_ITENS" NUMBER(5,0), 
	"NUM_MAX_DIAS_PRAZO" NUMBER(5,0), 
	"COD_HASH" VARCHAR2(60 CHAR), 
	"TIPO_TAREFA_ID" NUMBER(20,0)
   ) ;
