--------------------------------------------------------
--  DDL for Table TIPO_FINANCEIRO
--------------------------------------------------------

  CREATE TABLE "TIPO_FINANCEIRO" 
   (	"TIPO_FINANCEIRO_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"CODIGO" VARCHAR2(30 CHAR), 
	"NOME" VARCHAR2(60 CHAR), 
	"FLAG_PADRAO" CHAR(1 CHAR) DEFAULT 'N', 
	"TIPO_CUSTO" VARCHAR2(10 CHAR), 
	"FLAG_ATIVO" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_DESPESA" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_CONSID_HR_OS_CTR" CHAR(1 CHAR) DEFAULT 'S', 
	"COD_JOB" VARCHAR2(20 CHAR), 
	"FLAG_USA_BUDGET" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_USA_RECEITA_PREV" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_OBRIGA_CONTRATO" CHAR(1 CHAR) DEFAULT 'N'
   ) ;
