--------------------------------------------------------
--  DDL for Table TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "TIPO_DOCUMENTO" 
   (	"TIPO_DOCUMENTO_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"NOME" VARCHAR2(100 CHAR), 
	"CODIGO" VARCHAR2(40 CHAR), 
	"FLAG_ATIVO" CHAR(1 CHAR), 
	"FLAG_ARQ_EXTERNO" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_SISTEMA" CHAR(1 CHAR) DEFAULT 'N', 
	"TAM_MAX_ARQ" NUMBER(20,0), 
	"QTD_MAX_ARQ" NUMBER(5,0), 
	"EXTENSOES" VARCHAR2(100 CHAR), 
	"FLAG_TEM_APROV" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_TEM_COMEN" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_TEM_CIENC" CHAR(1 CHAR) DEFAULT 'S', 
	"FLAG_VISIVEL_CLI" CHAR(1 CHAR) DEFAULT 'N', 
	"ORDEM_CLI" NUMBER(5,0)
   ) ;
