--------------------------------------------------------
--  DDL for Table TIPO_PRODUTO_TRANSF
--------------------------------------------------------

  CREATE TABLE "TIPO_PRODUTO_TRANSF" 
   (	"TIPO_PRODUTO_TRANSF_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"NOME" VARCHAR2(500 CHAR), 
	"VARIACOES" VARCHAR2(4000 CHAR), 
	"CATEGORIA_ID" NUMBER(20,0), 
	"COD_CLASSE" VARCHAR2(500 CHAR), 
	"SUB_CLASSE" VARCHAR2(500 CHAR), 
	"CODIGOS_TIPO_OS" VARCHAR2(2000 CHAR), 
	"CUSTO_INTERNO_MIN" VARCHAR2(500 CHAR), 
	"CUSTO_INTERNO_MED" VARCHAR2(500 CHAR), 
	"CUSTO_INTERNO_MAX" VARCHAR2(500 CHAR), 
	"TEMPO_EXEC_INFO" VARCHAR2(500 CHAR), 
	"COD_EXT_PRODUTO" VARCHAR2(500 CHAR), 
	"CARGA_STATUS" VARCHAR2(10 CHAR), 
	"CARGA_DATA" DATE, 
	"CARGA_MOTIVO" VARCHAR2(4000 CHAR)
   ) ;
