--------------------------------------------------------
--  DDL for Table TIPO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "TIPO_CONTRATO" 
   (	"TIPO_CONTRATO_ID" NUMBER(20,0), 
	"EMPRESA_ID" NUMBER(20,0), 
	"CODIGO" VARCHAR2(20 CHAR), 
	"NOME" VARCHAR2(60 CHAR), 
	"COD_EXT_TIPO" VARCHAR2(20 CHAR), 
	"FLAG_ATIVO" CHAR(1 CHAR), 
	"FLAG_PADRAO" CHAR(1 CHAR), 
	"FLAG_TEM_HORAS" CHAR(1 CHAR), 
	"FLAG_TEM_FEE" CHAR(1 CHAR), 
	"TIPO_CONTRATANTE" VARCHAR2(10 CHAR), 
	"FLAG_VERIFI_PRECIF" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_VERIFI_HORAS" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_ELAB_CONTRATO" CHAR(1 CHAR) DEFAULT 'N', 
	"FLAG_ALOC_USUARIO" CHAR(1 CHAR) DEFAULT 'N'
   ) ;
