--------------------------------------------------------
--  DDL for Materialized View MV_USUARIO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "MV_USUARIO" ("USUARIO_ID", "PESSOA_ID", "APELIDO", "FUNCAO", "NOME_CARGO", "AREA_NOME", "CAMINHO", "PREFIXO", "NUMERO", "NOME_FISICO", "US_ROWID", "CA_ROWID", "AE_ROWID", "UC_ROWID", "PE_ROWID", "APE_ROWID", "AR_ROWID", "VO_ROWID")
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   CACHE 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FAST ON COMMIT
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT US.USUARIO_ID,
       PE.PESSOA_ID,
       PE.APELIDO,
       US.FUNCAO,
       CA.NOME AS NOME_CARGO,
       AE.NOME AS AREA_NOME,
       VO.CAMINHO,
       VO.PREFIXO,
       VO.NUMERO,
       AR.NOME_FISICO,
       US.ROWID AS US_ROWID,
       CA.ROWID AS CA_ROWID,
       AE.ROWID AS AE_ROWID,
       UC.ROWID AS UC_ROWID,
       PE.ROWID AS PE_ROWID,
       APE.ROWID AS APE_ROWID,
       AR.ROWID AS AR_ROWID,
       VO.ROWID AS VO_ROWID
  FROM USUARIO        US,
       CARGO          CA,
       AREA           AE,
       USUARIO_CARGO  UC,
       PESSOA         PE,
       (SELECT AP.PESSOA_ID,
               AP.ARQUIVO_ID,
               AP.ROWID AS APE_ROWID
          FROM ARQUIVO_PESSOA AP
         WHERE AP.TIPO_ARQ_PESSOA  = 'FOTO_USU'
           AND AP.TIPO_THUMB       = 'P' ) APE,
       ARQUIVO        AR,
       VOLUME         VO
 WHERE (US.USUARIO_ID       = UC.USUARIO_ID AND UC.DATA_FIM IS NULL)
   AND UC.CARGO_ID          = CA.CARGO_ID
   AND CA.AREA_ID           = AE.AREA_ID
   AND US.USUARIO_ID        = PE.USUARIO_ID (+)
   AND PE.PESSOA_ID         = APE.PESSOA_ID (+)
   AND APE.ARQUIVO_ID       = AR.ARQUIVO_ID (+)
   AND AR.VOLUME_ID         = VO.VOLUME_ID  (+);

   COMMENT ON MATERIALIZED VIEW "MV_USUARIO"  IS 'snapshot table for snapshot JOBONE_V4_174.MV_USUARIO';
